spring:

  jackson:
    serialization:
      fail-on-empty-beans: off

  config:
    import:
      application-aws.yml
  main:
    allow-circular-references: true

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
      enabled: true



  mvc:
    path match:
      matching-strategy: ant_path_matcher

  jpa:
    properties:
      hibernate:
    open-in-view: true
    hibernate:
      ddl-auto:  create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      use-new-id-generator-mappings: false


